#include "stdafx.h"

#include "level_4.h"


// PORTABLE 

/*

 Festivals of Vaisnava Calendar

*/


/*char * gp_Fest[] = { 
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Abhirama Thakura -- Disappearance",
NULL,
NULL,
"Srila Vrndavana Dasa Thakura -- Disappearance",
NULL,
NULL,
NULL,
NULL,
"Sri Gadadhara Pandita -- Appearance",
NULL,
NULL,
"Aksaya Trtiya. Candana Yatra starts./(Continues for 21 days)",
NULL,
NULL,
NULL,
"Jahnu Saptami",
NULL,
"Srimati Sita Devi (consort of Lord Sri Rama) -- Appearance#Sri Madhu Pandita -- Disappearance#Srimati Jahnava Devi -- Appearance",
NULL,
NULL,
"Rukmini Dvadasi",
"Sri Jayananda Prabhu -- Disappearance",
"Nrsimha Caturdasi: Appearance of Lord Nrsimhadeva",
"Krsna Phula Dola, Salila Vihara#Sri Paramesvari Dasa Thakura -- Disappearance#Sri Sri Radha-Ramana Devaji -- Appearance#Sri Madhavendra Puri -- Appearance#Sri Srinivasa Acarya -- Appearance",
NULL,
NULL,
NULL,
NULL,
"Sri Ramananda Raya -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Srila Vrndavana Dasa Thakura -- Appearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Baladeva Vidyabhusana -- Disappearance#Ganga Puja#Srimati Gangamata Gosvamini -- Appearance",
NULL,
NULL,
"Panihati Cida Dahi Utsava",
NULL,
"Snana Yatra#Sri Mukunda Datta -- Disappearance#Sri Sridhara Pandita -- Disappearance",
"Sri Syamananda Prabhu -- Disappearance",
NULL,
NULL,
NULL,
"Sri Vakresvara Pandita -- Appearance",
NULL,
NULL,
NULL,
NULL,
"Sri Srivasa Pandita -- Disappearance",
NULL,
NULL,
NULL,
NULL,
"Sri Gadadhara Pandita -- Disappearance#Srila Bhaktivinoda Thakura -- Disappearance",
NULL,
"Sri Svarupa Damodara Gosvami -- Disappearance#Sri Sivananda Sena -- Disappearance",
NULL,
NULL,
NULL, 
"Sri Vakresvara Pandita -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Guru (Vyasa) Purnima#Srila Sanatana Gosvami -- Disappearance",
NULL,
NULL,
NULL,
NULL,
"Srila Gopala Bhatta Gosvami -- Disappearance",
NULL,
NULL,
"Srila Lokanatha Gosvami -- Disappearance",
"The incorporation of ISKCON in New York",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Raghunandana Thakura -- Disappearance#Sri Vamsidasa Babaji -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Radha Govinda Jhulana Yatra begins",
"Srila Rupa Gosvami -- Disappearance#Sri Gauridasa Pandita -- Disappearance",
NULL,
NULL,
"Jhulana Yatra ends#Lord Balarama -- Appearance",
"Srila Prabhupada's departure for the USA",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Srimati Sita Thakurani (Sri Advaita's consort) -- Appearance",
"Lalita sasti",
NULL,
"Radhastami: Appearance of Srimati Radharani",
NULL,
NULL,
NULL,
"Sri Vamana Dvadasi: Appearance of Lord Vamanadeva#Srila Jiva Gosvami -- Appearance",
"Srila Bhaktivinoda Thakura -- Appearance",
"Ananta Caturdasi Vrata#Srila Haridasa Thakura -- Disappearance",
"Sri Visvarupa Mahotsava#Acceptance of sannyasa by Srila Prabhupada",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Srila Prabhupada's arrival in the USA",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Durga Puja",
NULL,
NULL,
"Ramacandra Vijayotsava#Sri Madhvacarya -- Appearance",
NULL,
"Srila Raghunatha Dasa Gosvami -- Disappearance#Srila Raghunatha Bhatta Gosvami -- Disappearance#Srila Krsnadasa Kaviraja Gosvami -- Disappearance",
NULL,
NULL,
"Sri Krsna Saradiya Rasayatra#Sri Murari Gupta -- Disappearance#Laksmi Puja",
NULL,
NULL,
NULL,
NULL,
"Srila Narottama Dasa Thakura -- Disappearance",
NULL,
NULL,
"Appearance of Radha Kunda, snana dana#Bahulastami",
"Virabhadra -- Appearance",
NULL,
NULL,
NULL,
NULL,
NULL,
"Dipa dana, Dipavali, (Kali Puja)",
"Bali Daityaraja Puja#Sri Rasikananda -- Appearance",
"Sri Vasudeva Ghosh -- Disappearance",
NULL,
"Srila Prabhupada -- Disappearance",
NULL,
NULL,
NULL,
"Gopastami, Gosthastami#Sri Gadadhara Dasa Gosvami -- Disappearance#Sri Dhananjaya Pandita -- Disappearance#Sri Srinivasa Acarya -- Disappearance",
"Jagaddhatri Puja",
NULL,
"Srila Gaura Kisora Dasa Babaji -- Disappearance",
NULL,
NULL,
"Sri Bhugarbha Gosvami -- Disappearance#Sri Kasisvara Pandita -- Disappearance",
"Sri Krsna Rasayatra#Tulasi-Saligrama Vivaha (marriage)#Sri Nimbarkacarya -- Appearance",
"Katyayani vrata begins",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Narahari Sarakara Thakura -- Disappearance",
"Sri Kaliya Krsnadasa -- Disappearance",
"Sri Saranga Thakura -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Odana sasthi",
NULL,
NULL,
NULL,
NULL,
"Advent of Srimad Bhagavad-gita",
NULL,
NULL,
NULL,
"Katyayani vrata ends",
NULL,
NULL,
NULL,
"Srila Bhaktisiddhanta Sarasvati Thakura -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Devananda Pandita -- Disappearance",
NULL,
"Sri Mahesa Pandita -- Disappearance#Sri Uddharana Datta Thakura -- Disappearance",
NULL,
NULL,
"Sri Locana Dasa Thakura -- Appearance",
NULL,
"Srila Jiva Gosvami -- Disappearance#Sri Jagadisa Pandita -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Jagadisa Pandita -- Appearance",
NULL,
NULL,
"Sri Krsna Pusya abhiseka",
NULL,
NULL,
NULL,
NULL,
"Sri Ramacandra Kaviraja -- Disappearance#Srila Gopala Bhatta Gosvami -- Appearance",
"Sri Jayadeva Gosvami -- Disappearance",
"Sri Locana Dasa Thakura -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Vasanta Pancami#Srimati Visnupriya Devi -- Appearance#Sarasvati Puja#Srila Visvanatha Cakravarti Thakura -- Disappearance#Sri Pundarika Vidyanidhi -- Appearance#Sri Raghunandana Thakura -- Appearance#Srila Raghunatha Dasa Gosvami -- Appearance",
NULL,
"Sri Advaita Acarya -- Appearance",
"Bhismastami",
"Sri Madhvacarya -- Disappearance",
"Sri Ramanujacarya -- Disappearance",
NULL,
"Varaha Dvadasi: Appearance of Lord Varahadeva",
"Nityananda Trayodasi: Appearance of Sri Nityananda Prabhu",
NULL,
"Sri Krsna Madhura utsava#Srila Narottama Dasa Thakura -- Appearance",
NULL,
NULL,
NULL,
NULL,
"Sri Purusottama Das Thakura -- Disappearance#Srila Bhaktisiddhanta Sarasvati Thakura -- Appearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Isvara Puri -- Disappearance",
NULL,
"Siva Ratri",
NULL,
"Srila Jagannatha Dasa Babaji -- Disappearance#Sri Rasikananda -- Disappearance",
NULL,
NULL,
"Sri Purusottama Dasa Thakura -- Appearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Madhavendra Puri -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Srivasa Pandita -- Appearance",
NULL,
NULL,
NULL,
"Sri Govinda Ghosh -- Disappearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Sri Ramanujacarya -- Appearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Damanaka-ropana dvadasi",
NULL,
NULL,
"Sri Balarama Rasayatra#Sri Krsna Vasanta Rasa#Sri Vamsivadana Thakura -- Appearance#Sri Syamananda Prabhu -- Appearance",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
};
*/
/*
int gp_Fasting[] = { NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
FAST_DUSK,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,// *Gadadhar-dis
FAST_NOON,// *bhaktivinoda
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
FAST_NOON,// *balarama*
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
FAST_NOON,// *radharani
NULL,NULL,NULL,
FAST_NOON,// *vamana
FAST_NOON,// *bhaktivinoda*
NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
FAST_NOON,// *srila prabhupada*
NULL,NULL,NULL,NULL,NULL,NULL,
FAST_NOON,// *gaura kisora*
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
FAST_NOON,// *bhaktisidhanta*
NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
FAST_NOON,// *advaita*
NULL,NULL,NULL,NULL,
FAST_NOON,// varaha
FAST_NOON,// nityananda
NULL,NULL,NULL,NULL,NULL,NULL,
FAST_NOON,//bhaktisidhanta
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL
};*/

/*
char * ekada shi_name[] = { "Varuthini Ekadasi",
"Mohini Ekadasi",
"Apara Ekadasi",
"Pandava Nirjala Ekadasi./(Total fast, even from water, if you have broken Ekadasi)",
"Yogini Ekadasi",
"Sayana Ekadasi",
"Kamika Ekadasi",
"Pavitropana Ekadasi",
"Annada Ekadasi",
"Parsva Ekadasi",
"Indira Ekadasi",
"Pasankusa Ekadasi",
"Rama Ekadasi",
"Utthana Ekadasi",
"Utpanna Ekadasi",
"Moksada Ekadasi",
"Saphala Ekadasi",
"Putrada Ekadasi",
"Sat-tila Ekadasi",
"Bhaimi Ekadasi",
"Vijaya Ekadasi",
"Amalaki vrata Ekadasi",
"Papamocani Ekadasi",
"Kamada Ekadasi",
"Parama Ekadasi",
"Padmini Ekadasi"
};
*/

