//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VCal5beta.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VCAL5BETA_DIALOG            102
#define CG_IDD_CALCULATIONCONTROLLER    103
#define CG_ID_VIEW_CALCULATIONCONTROLLER 104
#define CG_IDD_LOCATOR                  105
#define CG_ID_VIEW_LOCATOR              106
#define IDB_LIGHTBULB                   107
#define IDD_TIP                         108
#define CG_IDS_TIPOFTHEDAY              109
#define CG_IDS_TIPOFTHEDAYMENU          110
#define CG_IDS_DIDYOUKNOW               111
#define CG_IDS_FILE_ABSENT              112
#define CG_IDP_FILE_CORRUPT             113
#define CG_IDS_TIPOFTHEDAYHELP          114
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     130
#define IDD_SANKR                       132
#define IDD_NAKSATRAS                   133
#define IDD_OBSERVED_EVENT              135
#define IDD_COMPARE                     136
#define IDD_DIALOG2                     137
#define IDD_APP_DAY                     138
#define IDR_MAINMENU                    139
#define IDD_SELECT_LOCATION             140
#define IDR_ACCELERATOR1                141
#define IDD_MASALIST                    142
#define IDD_SET_DATE                    143
#define IDD_FIND_MHD                    144
#define IDD_GET_LOCATION                145
#define IDD_GET_DATE                    146
#define IDD_DIALOG3                     147
#define IDD_GET_YEAR                    148
#define IDD_GET_DATE_RANGE              149
#define IDD_SELECT_LANG                 150
#define IDD_GET_LOCATION_EX             151
#define IDD_CREATE_LOCATION             152
#define IDD_SET_AYANAMSA                153
#define IDD_CUSTOM_EVENTS               154
#define IDD_EVENTS_1                    155
#define IDD_GET_GAUBD_TM                156
#define IDD_EVENTS_GET_TEXT             157
#define IDD_CALC_PROGRESS               158
#define IDD_EDIT_CUSTOM_EVENT           159
#define IDD_DIALOG4                     160
#define IDD_PAGE_ASTRO                  161
#define IDD_PAGE_ASTROV                 162
#define IDD_PAGE_FEST                   163
#define IDD_PAGE_GENERAL                164
#define IDD_PRINT_STYLE                 165
#define IDB_BITMAP2                     169
#define IDB_BITMAP1                     170
#define IDR_FINDMENU                    171
#define IDD_END_DATE                    172
#define IDD_CALCEVENTS_TYPES            173
#define IDR_LOCSMENU                    174
#define IDR_EVENTSFRAME                 175
#define IDR_EVENTSMENU                  175
#define IDD_NEW_COUNTRY                 179
#define IDD_RENAME_COUNTRY              180
#define IDD_STRING_MANAGER              181
#define IDD_EDIT_STRING                 182
#define IDI_CALC_CALENDAR               183
#define IDI_CALC_APPDAY                 184
#define IDI_SET_MYLOC                   185
#define IDI_HELP                        186
#define IDI_FINDEVENT                   187
#define IDD_TIP_OF_DAY                  188
#define IDD_SPEC_COMMAND                189
#define IDC_BULB                        1000
#define IDC_EDIT1                       1001
#define IDC_STARTUP                     1001
#define IDC_LIST1                       1002
#define IDC_NEXTTIP                     1002
#define IDC_EDIT2                       1003
#define IDC_EDIT3                       1004
#define IDC_TIPSTRING                   1004
#define IDC_EDIT4                       1005
#define IDC_COMBO1                      1006
#define IDC_BUTTON1                     1007
#define IDC_EDIT5                       1008
#define IDC_COMBO2                      1009
#define IDC_EDIT6                       1010
#define IDC_EDIT7                       1011
#define IDC_BUTTON2                     1012
#define IDC_BUTTON3                     1014
#define IDC_BUTTON4                     1015
#define IDC_SAVE_XML                    1016
#define IDC_COMBO_DST                   1017
#define IDC_BUTTON5                     1018
#define IDC_BUTTON6                     1019
#define IDC_BUTTON7                     1020
#define IDC_CHECK1                      1023
#define IDC_CHECK18                     1024
#define IDC_CHECK3                      1026
#define IDC_CHECK6                      1029
#define IDC_CHECK7                      1030
#define IDC_CHECK8                      1031
#define IDC_CHECK9                      1032
#define IDC_CHECK10                     1033
#define IDC_CHECK11                     1034
#define IDC_CHECK12                     1035
#define IDC_CHECK13                     1036
#define IDC_CHECK14                     1037
#define IDC_CHECK15                     1038
#define IDC_CHECK16                     1039
#define IDC_CHECK17                     1040
#define IDC_BUTTON10                    1043
#define IDC_BUTTON11                    1044
#define IDC_EDIT_DATE                   1048
#define IDC_LOCATION                    1049
#define IDC_TREE1                       1051
#define IDC_SET_LOCATION                1052
#define IDC_EDIT8                       1054
#define IDC_CHECK2                      1056
#define IDC_PROGRESS1                   1057
#define IDC_CHECK19                     1057
#define IDC_MONTHCALENDAR1              1058
#define IDC_BUTTON_START                1059
#define IDC_COMBO_KIND                  1062
#define IDC_COMBO_KIND1                 1062
#define IDC_COMBO_EVENT                 1063
#define IDC_COMBO_EVENT1                1063
#define IDC_BUTTON_TOCALENDAR           1064
#define ID_BUTTON_BACK                  1065
#define ID_BUTTON_NEXT                  1066
#define IDC_BUTTON_BACK                 1067
#define IDC_BUTTON_NEXT                 1068
#define IDC_COMBO3                      1075
#define IDC_PLACE1                      1078
#define IDC_COMBO6                      1081
#define IDC_COMBO7                      1082
#define IDC_STATIC1                     1083
#define IDC_LIST2                       1084
#define IDC_STATIC2                     1085
#define IDC_STATIC_DST_INFO1            1086
#define IDC_STATIC_DST_INFO2            1087
#define IDC_STATIC_DST_INFO0            1088
#define IDC_BUTTON_EDIT                 1089
#define IDC_STATIC_VER                  1090
#define IDC_BUTTON_LINK                 1091
#define IDC_CHECK4                      1092
#define IDC_CHECK5                      1093
#define IDC_RADIO1                      1094
#define IDC_RADIO2                      1095
#define IDC_COMBO_COUNTRY               1096
#define IDC_COMBO_EVENT3                1097
#define IDC_COMBO_KIND2                 1098
#define IDC_COMBO_KIND3                 1099
#define IDC_COMBO_EVENT2                1100
#define IDC_BUTTON_LISTTOCAL            1101
#define IDC_BUTTON_SELECT_FONT          1102
#define IDC_COMBO4                      1104
#define IDC_DST_INFO                    1105
#define IDC_RADIO3                      1106
#define IDC_RADIO4                      1107
#define IDC_RADIO5                      1108
#define IDC_RADIO6                      1109
#define IDC_RADIO7                      1110
#define IDC_STATIC_1                    1111
#define IDC_BUTTON_SET                  1112
#define IDC_STATIC_TZ                   1113
#define IDC_BTN_LATI                    1114
#define IDC_BTN_LONG                    1115
#define IDC_LATI_DEG                    1116
#define IDC_LONG_DEG                    1117
#define IDC_LATI_ARC                    1118
#define IDC_LONG_ARC                    1119
#define ID_CALCULATE_CALENDAR           32771
#define ID_CALCULATE_NAKSATRAS          32772
#define ID_CALCULATE_SANKRANTIS         32773
#define ID_CALCULATE_APPEARANCEDAY      32774
#define ID_CALCULATE_TITHITIMING        32775
#define ID_EXPORT_CALENDAR              32776
#define ID_EXPORT_NAKSATRATIMES         32777
#define ID_EXPORT_SANKRANTIS            32778
#define ID_EXPORT_TITHITIMINGS          32779
#define ID_EXPORT_EVENTS                32780
#define ID_TOOLS_COMPAREIMPORTEDFILE    32781
#define ID_EXPORT_LOCATIONSLIST         32782
#define ID_TOOLS_CALENDARLISTSETTINGS   32783
#define ID_SETTINGS_CALENDARLIST        32783
#define ID_HELP_ABOUT                   32784
#define ID_EDIT_CLEARSELECTION          32787
#define ID_EDIT_SELECTALL               32788
#define ID_CALCULATE_MASALISTING        32789
#define ID_TOOLS_NEWWINDOW              32790
#define ID_FIND_MHD                     32791
#define ID_FILE_EXIT                    32792
#define ID_WINDOW_CLOSE                 32793
#define ID_CALCULATE_TODAY              32794
#define ID_CALCULATE_NEXTDAY            32795
#define ID_CALCULATE_PREVIOUSDAY        32796
#define ID_SETTINGS_MYLOCATION          32797
#define ID_SETTINGS_LANGUAGE_OUTPUT     32798
#define ID_SETTINGS_LOCATIONS           32799
#define ID_SETTINGS_AYANAMSAVALUE       32800
#define ID_SETTINGS_MYEVENTS            32801
#define ID_FILE_PRINT1                  32802
#define ID_EVENT_FIND                   32803
#define ID_LOCATION_SETLOCATION         32807
#define ID_SET_START_MONTH              32808
#define ID_SET_START_MASA               32809
#define ID_SET_START_YEAR               32810
#define ID_SET_START_GYEAR              32811
#define ID_SET_TODAY                    32812
#define ID_CALCULATE_EVENTS             32813
#define ID_LIST_IMPORT                  32814
#define ID_LIST_RESET                   32815
#define ID_LOCATION_CREATELOCATION      32816
#define ID_LOCATION_EDITLOCATION        32817
#define ID_LOCATION_DELETELOCATION      32818
#define ID_GOOGLE_SHOWLOCATION          32819
#define ID_FILE_EXPORTLIST              32820
#define ID_FILE_CLOSEWINDOW             32821
#define ID_EVENTS_CLOSE                 32822
#define ID_BUTTON32823                  32823
#define ID_EVENTS_NEWEVENT              32824
#define ID_EVENTS_EDITEVENT             32825
#define ID_EVENTS_DELETEEVENT           32826
#define ID_COUNTRY_ADDCOUNTRY           32827
#define ID_COUNTRY_RENAMECOUNTRY        32828
#define ID_FILE_STRINGMANAGER           32829
#define ID_SETTINGS_TEXTVIEW            32830
#define ID_SETTINGS_RICHTEXTVIEW        32831
#define ID_SETTINGS_TEXTSIZE10          32832
#define ID_SETTINGS_TEXTSIZE11          32833
#define ID_SETTINGS_TEXTSIZE12          32834
#define ID_SETTINGS_TEXTSIZE13          32835
#define ID_SETTINGS_TEXTSIZE14          32836
#define ID_HELP_SHOWSTARTUPTIPS         32838
#define ID_HELP_OFFLINEHELP             32839
#define ID_HELP_HELPTOPICTHISWINDOW     32840
#define ID_HELP_HELPTOPICQUICKGUIDE     32841
#define ID_HELP_HELP                    32842
#define ID_SETTINGS_AYANAMSA            32848

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
